services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully

  migrations:
    image: backend:latest
    env_file:
      - .env
    command: alembic upgrade head
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine3.23
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    
  

volumes:
  pg_data:
  redis_data: