services:
  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl:ro
    depends_on:
      backend:
        condition: service_started

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: backend:latest
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
  celery:
    build:
      context: ./backend
      dockerfile: Dockerfile.worker
    image: backend-worker:latest
    env_file:
      - .env
    working_dir: /code
    command: celery -A worker.celery_app worker -l info -c 1
    volumes:
      - ./backend:/code
    depends_on:
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
    shm_size: "1gb"

  celery-beat:
    image: backend-worker:latest
    env_file:
      - .env
    working_dir: /code
    command: celery -A worker.celery_app beat -l info
    volumes:
      - ./backend:/code
    depends_on:
      redis:
        condition: service_started
      migrations:
        condition: service_completed_successfully
    restart: unless-stopped
  migrations:
    image: backend:latest
    env_file:
      - .env
    command: alembic upgrade head
    volumes:
      - ./backend:/code
    depends_on:
      db:
        condition: service_healthy

  db:
    image: postgres:18-alpine3.23
    env_file:
      - .env
    volumes:
      - ./volumes/postgresql:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:8-alpine
    env_file:
      - .env
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    
  qdrant:
    image: qdrant/qdrant:v1.17.1
    env_file:
      - .env
    volumes:
      - ./volumes/qdrant:/qdrant/storage


volumes:
  redis_data:
