services:
  backend:
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/code
    ports:
      - "${BACKEND_PORT}:8000"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    env_file:
      - .env
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/code
      - frontend_node_modules:/code/node_modules

  migrations:
    volumes:
      - ./backend:/code

  db:
    ports:
      - "${POSTGRES_PORT}:5432"
  qdrant:
    image: qdrant/qdrant:v1.17.1
    env_file:
      - .env
    ports:
      - "${QDRANT_PORT}:6333"
    volumes:
      - qdrant_storage:/qdrant/storage


volumes:
  frontend_node_modules:


  
