"""empty message

Revision ID: 0f6554cb56a9
Revises: 5308f270268a
Create Date: 2026-04-03 19:56:22.262582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f6554cb56a9'
down_revision: Union[str, Sequence[str], None] = '5308f270268a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source', 'region_code')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('region_code', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
