"""

Revision ID: 33d35427ebb1
Revises: 0f6554cb56a9
Create Date: 2026-04-14 22:02:56.680259

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33d35427ebb1'
down_revision: Union[str, Sequence[str], None] = '0f6554cb56a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('compressed_up_to_message_id', sa.Integer(), nullable=True))
    op.add_column('chats', sa.Column('last_total_tokens', sa.Integer(), nullable=False))
    op.add_column('chats', sa.Column('reserve_input_tokens', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'reserve_input_tokens')
    op.drop_column('chats', 'last_total_tokens')
    op.drop_column('chats', 'compressed_up_to_message_id')
    # ### end Alembic commands ###
