"""empty message

Revision ID: 3d9a2f032b09
Revises: d35d92f1f080
Create Date: 2026-04-01 16:26:33.287254

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d9a2f032b09'
down_revision: Union[str, Sequence[str], None] = 'd35d92f1f080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('place_of_work', sa.String(length=200), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'place_of_work')
    # ### end Alembic commands ###
