"""

Revision ID: 48c3784836c6
Revises: 33d35427ebb1
Create Date: 2026-04-17 13:57:36.094062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '48c3784836c6'
down_revision: Union[str, Sequence[str], None] = '33d35427ebb1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chunks', 'source_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=True)
    op.add_column('source', sa.Column('document_type', sa.String(length=32), nullable=False))
    op.add_column('source', sa.Column('place_of_work', sa.String(length=255), nullable=True))
    op.drop_column('source', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('source', 'place_of_work')
    op.drop_column('source', 'document_type')
    op.alter_column('chunks', 'source_name',
               existing_type=sa.VARCHAR(length=255),
               nullable=False)
    # ### end Alembic commands ###
