"""empty message

Revision ID: b4f5b573914c
Revises: 492933b950a9
Create Date: 2026-04-19 18:45:54.008359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b4f5b573914c'
down_revision: Union[str, Sequence[str], None] = '492933b950a9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('region_reg', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('region_current', sa.String(length=200), nullable=True))
    op.add_column('users', sa.Column('persistent_memory', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'persistent_memory')
    op.drop_column('users', 'region_current')
    op.drop_column('users', 'region_reg')
    # ### end Alembic commands ###
