"""empty message

Revision ID: d35d92f1f080
Revises: 20e16a0bb63e
Create Date: 2026-03-24 23:38:28.232306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd35d92f1f080'
down_revision: Union[str, Sequence[str], None] = '20e16a0bb63e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chats', sa.Column('compressed_context', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chats', 'compressed_context')
    # ### end Alembic commands ###
