use_default_settings:
  engines:
    keep_only:
      - google
      - brave
      - duckduckgo
      - yandex

general:
    instance_name: "SOC Assistant Search"
    donation_url: false
    contact_url: false
    enable_metrics: false

server:
    secret_key: "!env SEARXNG_SECRET"
    limiter: false
    image_proxy: false
    method: "GET"

ui:
    static_use_hash: true
    default_locale: "ru"

search:
    safe_search: 0
    autocomplete: ""
    default_lang: "ru"
    formats:
        - html
        - json

valkey:
    url: redis://redis:6379/5

engines:
    - name: yandex
      timeout: 4.0

    - name: google
      timeout: 4.0

    - name: brave
      timeout: 4.0

    - name: duckduckgo
      timeout: 4.0

